kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kc
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 30080
        hostPort: 80
        listenAddress: "127.0.0.1"
        protocol: TCP
    labels:
      exposed: "true"
  - role: worker
