version: '3'
env:
  KIND_CLUSTER_NAME: my-kind-cluster
  KIND_CONFIG: kind.config.yaml
  NGF_VALUES: values/ngf/values.yaml
  NGF_NAMESPACE: nginx-gateway
tasks:
  default:
    desc: Show the available tasks
    cmd: task --list
    silent: true
  fmt:
    desc: Format yaml files
    cmd: yamlfmt .
  kind:create:
    desc: Create a new kind cluster
    cmd: kind create cluster --name {{.KIND_CLUSTER_NAME}} --config {{.KIND_CONFIG}}
  kind:delete:
    desc: Delete the kind cluster
    cmd: kind delete cluster --name {{.KIND_CLUSTER_NAME}}
  setup:
    desc: Setup the kind cluster
    cmds:
      # Install Gateway API CRDs
      - kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/standard-install.yaml
      # Install Nginx Gateway Fabric
      - helm upgrade ngf oci://ghcr.io/nginx/charts/nginx-gateway-fabric --create-namespace -n {{.NGF_NAMESPACE}} --install --values {{.NGF_VALUES}}
