version: '3'
env:
  KIND_CLUSTER_NAME: my-kind-cluster
  KIND_CONFIG: kind.config.yaml
tasks:
  default:
    desc: Show the available tasks
    cmd: task --list
    silent: true
  kind:create:
    desc: Create a new kind cluster
    cmd: kind create cluster --name {{.KIND_CLUSTER_NAME}} --config {{.KIND_CONFIG}}
  kind:delete:
    desc: Delete the kind cluster
    cmd: kind delete cluster --name {{.KIND_CLUSTER_NAME}}
  setup:
    desc: Setup the kind cluster
    cmds:
      # Create a sample application
      - kubectl apply -f manifests/host-hello.yaml
      # Install NGINX Gateway Fabric
      - kubectl kustomize "https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v1.6.2" | kubectl apply -f -
      - helm upgrade ngf oci://ghcr.io/nginx/charts/nginx-gateway-fabric --create-namespace -n nginx-gateway --values nginx-gw-values.yaml --set service.create=false --install
      - kubectl apply -f manifests/host-gateway.yaml
